param(
  [string]$SyncPath,
  [string]$ServerPath
)
$ErrorActionPreference='Stop'
if ([string]::IsNullOrWhiteSpace($SyncPath) -or [string]::IsNullOrWhiteSpace($ServerPath)) {
  $artifactRoot = Join-Path $PSScriptRoot '..\artifacts'
  $latest = Get-ChildItem -LiteralPath $artifactRoot -Directory -Filter 'MyFrame-*-win-x64' |
    Sort-Object LastWriteTime -Descending | Select-Object -First 1
  if ($null -eq $latest) { throw 'MCP_DISTRIBUTION_NOT_FOUND' }
  if ([string]::IsNullOrWhiteSpace($SyncPath)) { $SyncPath = Join-Path $latest.FullName 'MyFrame.Sync.exe' }
  if ([string]::IsNullOrWhiteSpace($ServerPath)) { $ServerPath = Join-Path $latest.FullName 'MyFrame.Mcp.exe' }
}
$sync=(Resolve-Path -LiteralPath $SyncPath).Path
$suffix=[guid]::NewGuid().ToString('N'); $now=(Get-Date).ToUniversalTime().ToString('O'); $root=Join-Path ([IO.Path]::GetTempPath()) "my-frame-econ-$suffix"; $inv=Join-Path $root 'inventory'; $pub=Join-Path $root 'public'; New-Item -ItemType Directory -Path $inv,$pub | Out-Null
try {
  $capture=[ordered]@{equipment=@([ordered]@{instanceId='mesa-1';typeId='/Lotus/Warframes/MesaPrime';rank=30});stackables=@([ordered]@{typeId='/Lotus/Parts/MesaPrimeChassis';quantity=2},[ordered]@{typeId='/Lotus/Parts/MesaPrimeSystems';quantity=1})}; $payload=$capture|ConvertTo-Json -Depth 8 -Compress; $eventId=[guid]::NewGuid(); $envelope=[ordered]@{schemaVersion=1;gameId=8954;source='overwolf-native';kind='inventory';sessionId=([guid]::NewGuid().ToString('D'));eventId=$eventId.ToString('D');sequence=1;receivedAt='2026-09-13T12:00:00Z';providerVersion='smoke';encoding='json-object';completeness='unverified';payload=$payload}; $body=[Text.Encoding]::UTF8.GetBytes(($envelope|ConvertTo-Json -Depth 8 -Compress)); $bodyName="$($eventId.ToString('D')).capture.json"; [IO.File]::WriteAllBytes((Join-Path $inv $bodyName),$body); $hash=[Security.Cryptography.SHA256]::Create(); try{$digest=$hash.ComputeHash($body)}finally{$hash.Dispose()}; $hex=($digest|ForEach-Object {$_.ToString('x2')}) -join ''; $marker=[ordered]@{schemaVersion=1;fileName=$bodyName;bytes=$body.Length;sha256=$hex}; [IO.File]::WriteAllText((Join-Path $inv "$($eventId.ToString('D')).ready.json"),($marker|ConvertTo-Json -Depth 8 -Compress))
  $catalog=[ordered]@{uniqueName='/Lotus/Warframes/MesaPrime';name='Mesa Prime';category='Warframes';masterable=$true;prime=$true;marketId='set-id';marketSlug='mesa-prime';components=@([ordered]@{uniqueName='/Lotus/Parts/MesaPrimeChassis';name='Chassis';itemCount=1;ducats=15;tradable=$true;marketId='chassis-id';marketSlug='mesa_prime_chassis'},[ordered]@{uniqueName='/Lotus/Parts/MesaPrimeSystems';name='Systems';itemCount=1;ducats=15;tradable=$true;marketId='systems-id';marketSlug='mesa_prime_systems'}); }; $catalogJson=($catalog|ConvertTo-Json -Depth 10 -Compress); [IO.File]::WriteAllText((Join-Path $pub 'Export.json'),"[$catalogJson]")
  $quotes=[ordered]@{mesa_prime_chassis=[ordered]@{slug='mesa_prime_chassis';lowestSell=15;highestBuy=10;retrievedAt=$now;isStale=$false};mesa_prime_systems=[ordered]@{slug='mesa_prime_systems';lowestSell=$null;highestBuy=$null;retrievedAt=$now;isStale=$false}}; [IO.File]::WriteAllText((Join-Path $root 'market-quotes.json'),($quotes|ConvertTo-Json -Depth 8 -Compress))
  $market=[ordered]@{account=[ordered]@{id='acct-1';ingameName='tester';platform='pc'};orders=@([ordered]@{id='order-1';itemId='chassis-id';itemSlug='mesa_prime_chassis';type='sell';platinum=15;quantity=1;visible=$true});retrievedAt=$now;validationState='confirmed'}; [IO.File]::WriteAllText((Join-Path $root 'market-data.dat'),($market|ConvertTo-Json -Depth 8 -Compress)); [IO.File]::WriteAllText((Join-Path $root 'market-items.dat'),('{"byNormalizedName":{},"retrievedAt":"'+$now+'"}')); [IO.File]::WriteAllText((Join-Path $root 'settings.v1.json'),('{"storageVersion":1,"revision":1,"alecaFrameDirectory":"","ducatsPerPlatinum":10,"unvaultedPrimeSetsToReserve":0,"updatedAt":"'+$now+'"}'))
  Write-Output (& $sync --overwolf-inventory-directory $inv --allow-raw --data-root $root)
  Write-Output (& $sync --public-export-directory $pub --data-root $root)
  $server=(Resolve-Path -LiteralPath $ServerPath).Path
  foreach($tool in @('get_overview','list_sales','list_surplus')) { $out=Join-Path $root "$tool.json"; $err=Join-Path $root "$tool.err"; $args=@('--yes','@modelcontextprotocol/inspector','--cli',$server,'-e',"MYFRAME_DATA_ROOT=$root",'--method','tools/call','--tool-name',$tool,'--format','json'); $p=Start-Process -FilePath 'npx.cmd' -ArgumentList $args -WorkingDirectory (Split-Path $server) -Wait -PassThru -NoNewWindow -RedirectStandardOutput $out -RedirectStandardError $err; $line=Get-Content $out | Where-Object {$_ -match '^\{"result"'} | Select-Object -Last 1; if(-not $line){throw "No JSON result for ${tool}: $(Get-Content -Raw $err)"}; $s=($line|ConvertFrom-Json).result.structuredContent; if($tool -eq 'get_overview'){[pscustomobject]@{tool=$tool;prices=$s.meta.sources.prices.state;orders=$s.meta.sources.orders.state;availabilityConfirmed=$s.meta.availabilityConfirmed;warnings=(@($s.meta.warnings|ForEach-Object code)-join ',');saleRecommendations=$s.overview.saleRecommendations;surplusParts=$s.overview.surplusParts}} else {[pscustomobject]@{tool=$tool;count=$s.count;items=(@($s.items|ForEach-Object {"$($_.name)|action=$($_.action)|owned=$($_.owned)|reserved=$($_.reserved)|orders=$($_.reservedForOrders)|available=$($_.availableToSell)|each=$($_.platinumEach)|total=$($_.totalPlatinum)|reason=$($_.reasonCode)"})-join ';');totals=($s.totals|ConvertTo-Json -Compress)}} }
} finally { if(Test-Path $root){Remove-Item $root -Recurse -Force} }
